### ISSUE TITLE
Service fails when request is made

### ISSUE THREAD

**Issue by 0x234** [hunterlong/gethexporter#1]
`curl localhost:9090/metrics`

```
2019/01/10 08:12:08 http: panic serving [::1]:41566: runtime error: invalid memory address or nil pointer dereference
```

**Comment by 0x234** [comment]
This happens if the geth instance does not have `:8545` added to the `GETH` env

**Comment by hunterlong** [comment]
I fixed the panic from happening. Also added a `ADDRESSES` ENV var that can log specific wallet addresses.
